### ISSUE TITLE
More misc TODO 

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#68]
# Pedigo
 - [x] merge ptr changes [#67]
 - [x] constant multiplier kwarg for diag aug
 - [x] figure out ASE/eleganz bug/feature
 - [x] fix LSE is_almost_symmetric behavior
 - [ ] write some tutorials and/or show use on real data
 - [ ] transformations
   - [ ] look into sklearn preprocessing [#52]
   - [ ] implement log transform
   - [ ] refactor plotting log transform to use above 
   - [ ] refactor transform funcs out of utils (match docs) 
 - [x] run ase with diag aug on eleganz data with several constant multipliers [#59]

**Comment by j1c** [comment]
- [ ] Refactor LCC to embedding instead of import_graph
- [ ] Check for label counts in pairplot. If <= 1, throw an error since you cant compute kde with 1 sample
